### ISSUE TITLE
Failed to build neovim on github action

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#15332]
Sorry to open issue without issue temple, because I can not build neovim, so the version is empty.

I want to build neovim and run plugin test in github action. but I got following error when build neovim:

```
[66/106] No build step for 'libvterm'
[67/106] Performing install step for 'libvterm'
FAILED: build/src/libvterm-stamp/libvterm-install /tmp/tmp.dQyVTgqc4m/.deps/build/src/libvterm-stamp/libvterm-install 
cd /tmp/tmp.dQyVTgqc4m/.deps/build/src/libvterm-build && /usr/bin/make CC=/usr/bin/cc PREFIX=/tmp/tmp.dQyVTgqc4m/.deps/usr CFLAGS=-fPIC LDFLAGS+=-static CFLAGS+=-Og CFLAGS+=-g install && /usr/local/bin/cmake -E touch /tmp/tmp.dQyVTgqc4m/.deps/build/src/libvterm-stamp/libvterm-install
make[1]: Entering directory '/tmp/tmp.dQyVTgqc4m/.deps/build/src/libvterm-build'
make[1]: *** No rule to make target 'install'.  Stop.
make[1]: Leaving directory '/tmp/tmp.dQyVTgqc4m/.deps/build/src/libvterm-build'
```

here is action config:

```
    runs-on: ubuntu-18.04
    env:
        VIM_BIN: ${{ matrix.vimbin }}
        VIM_TAG: ${{ matrix.vimtag }}
        DEPS: /home/runner/work/SpaceVim/deps
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake gcc-multilib gettext gperf libtool-bin locales ninja-build pkg-config unzip python3-pip python-pip libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev python3-dev ruby-dev lua5.1 liblua5.1-dev libperl-dev ninja-build
```
