### ISSUE TITLE
nvim_out_write has bug when string length > 4095

### ISSUE THREAD

**Issue by Freed-Wu** [neovim/neovim#20534]
### Neovim version (nvim -v)

0.7.2

### Vim (not Nvim) behaves the same?

no, 9.0

### Operating system/version

linux 5.19.7

### Terminal name/version

kitty 0.26.2

### $TERM environment variable

tmux-256color

### Installation

pacman

### How to reproduce the issue

`yaml2json.py`

```python
#!/usr/bin/env python
import sys
import json

import yaml

ret = []
contexts = yaml.load(open(sys.argv[-1]), yaml.CLoader).get("contexts", {})
for context in sum(contexts.values(), []):
    scopes = context.get("scope", "").split(" ")
    for scope in scopes:
        scope = scope.rpartition(".")[0]
        if scope:
            match = context.get("match", "")
            ret += [{"word": scope, "menu": match}]
print(json.dumps(ret))
```

for neovim:

```vim
  python sys.argv = ['/path/to/cmd-help-sublime-syntax/syntaxes/cmd-help.sublime-syntax']
  redir > /dev/shm/c.json
  silent! execute 'pyfile /path/to/yaml2json.py'
  redir END
```

Then you can find `/dev/shm/c.json` is not a correct json. Its 4096-th character should be `:`, however, it become `\n`.

For vim:

```vim
  python3 sys.argv = ['/path/to/cmd-help-sublime-syntax/syntaxes/cmd-help.sublime-syntax']
  redir > /dev/shm/d.json
  silent! execute 'py3file /path/to/yaml2json.py'
  redir END
```

`/dev/shm/d.json` is a correct json.

This is `cmd-help.sublime-syntax`:

```yaml
%YAML 1.2
---
name: Command Help
# don't really exist, but useful for the shortname
file_extensions:
  - cmd-help
  - help
scope: text.cmd-help


variables:
### section name variables:
  # words regardless of case, including dashes for compound words
  any_word: '[A-Za-z][A-Za-z-]*\b'
  # allow parentheses on both ends of the word
  any_word2: '\(?{{any_word}}\)?'
  # words starting with uppercase
  leading_word: '[A-Z][A-Za-z-]*\b'
  # only consider lines <= 40 chars long
  lookahead_40: '(?=.{1,40}\n)'

### command option variables:
  option_break: '[ \t\n,=\[</:]'
  # marks seen in options: . ? : # $ -- +
  option_char: '[^{{option_break}}]'
  option_name: '{{option_char}}+'

### command/option argument variables:
  ellipsis: '\.\.\.'
  allcaps_argument_name: '[A-Z][0-9A-Z_-]*\b'
  relaxed_argument_name: '[A-Za-z][0-9A-Za-z_-]*\b'

### other-def variables:
  other_lowercase_name: '[a-z][0-9a-z_-]*\b'
  long_space: '   |\t|\n|{{single_2_space}}'
  single_2_space: '  (?!.*\S  \S)'

### file-def variables:
  filename: '[0-9a-zA-Z._-]+'
  absolute_path: '/{{filename}}(/{{filename}})*'
  relative_path: '{{filename}}/({{filename}}/)*{{filename}}'

### exceptions variables:
  color_code_begin: '(?=.*\e\[.*'
  color_code_end: '.*(?<=[0-9])m)'

scope_variables: # last scope is matched first
  - &SECTION_HEADING_SCOPES
    constant.section-heading.cmd-help  string.section-heading.cmd-help
    markup.heading.cmd-help  entity.name.section.cmd-help
  - &INLINE_USAGE_SCOPES
    constant.section-heading.cmd-help  string.inline-usage.cmd-help
    markup.heading.inline-usage.cmd-help  entity.name.section.inline-usage.cmd-help

  - &OPTION_DEF_SCOPES
    entity.name.function.option.cmd-help
  - &OPTION_ARGUMENT_SCOPES
    string.option-argument.cmd-help  variable.other.option-argument.cmd-help
    variable.parameter.option-argument.cmd-help

  # argument definitions (99% confidence)
  - &ARGUMENT_DEF_SCOPES # =~ option argument
    string.argument.cmd-help  variable.other.argument.cmd-help
    variable.parameter.argument.cmd-help
  # mostly all-caps definitions. usually environment variables or arguments
  - &OTHER_VAL_DEF_SCOPES # =~ option argument
    string.other-value.cmd-help  variable.other.other-value.cmd-help
    variable.parameter.other-value.cmd-help

  # non all-caps definitions: subcommands, argument enums, etc.
  - &OTHER_DEF_SCOPES
    keyword.other.def.cmd-help # support.function variable.function ?

  - &FILE_DEF_SCOPES
    constant.file.cmd-help
    # variable.other.readwrite.file.cmd-help  string.file.cmd-help


contexts:
  prototype:
    # abort if color escape codes
    - include: color-escape-codes-sink
    # abort if formatted with backspaces
    - match: (?=.*[\b])
      set: sink

  main: # entry point only, main-b is the real main
    - meta_include_prototype: false
    - include: first-line-specials
    - match: ^
      set: main-b

  first-line-specials:
    - include: ignore-syntax-test-header
    # man page first line: ^cmd/fn_name(man_section_digit) ... idem$
    - match: (?=^([A-Z-]+)\(([0-9])\)\s.+\s\1\(\2\)$)
      push:
        - clear_scopes: true
        - include: Manpage.sublime-syntax

  main-b: # stack lv 0
    - match: ^
      push: [line, line-begin]

  line: # stack lv 1
    - match: $
      pop: true

  ### helpers ##################################################################

  else-pop:
    - include: eol-pop # '.' doesn't match '\n'
    - match: (?=.)
      pop: true

  eol-pop:
    - match: \n
      pop: true

  then-pop:
    - match: ''
      pop: true

  de-scope-match:
    - clear_scopes: 1
    - include: then-pop

  sink:
    - clear_scopes: true
    - meta_include_prototype: false

  ### stack lv 2 ###############################################################

  line-begin:
    - match: ^(?=\S)
      set: indent-0
    - match: ^ {1,2}(?=\S)
      set: indent-1-2
    - match: ^ {3,8}(?=\S)
      set: indent-3-8
    - match: ^\t{1,2}(?=\S)
      set: indent-3-8
    - include: else-pop

  indent-0:
    - include: heading
    - include: option-def-head
    - include: argument-def
    - include: other-def
    - include: else-pop

  indent-1-2:
    - include: option-def-head
    - include: heading
    - include: argument-def
    - include: other-def
    - include: else-pop

  indent-3-8:
    - include: option-def-head
    - include: argument-def
    - include: other-def
    - include: else-pop

  ### section headings #########################################################

  heading:
    - include: heading-specials
    - match: '{{lookahead_40}}{{leading_word}}( {{any_word2}})*:?\n'
      scope: *SECTION_HEADING_SCOPES
      set: then-pop
    # - match: '{{any_word2}}( {{any_word2}})*:\n'
    #   scope: *SECTION_HEADING_SCOPES
    #   set: then-pop

  heading-specials:
    - match: (?i:usage):(?=.+\n)
      scope: *INLINE_USAGE_SCOPES
      set: then-pop
    - include: python-argparse-headings

  ### option definitions #######################################################

  option-def-head:
    - include: option-def-specials
    - match: --- # probably a separator
      pop: true
    - include: option-def

  option-def:
    - match: -{{option_name}}
      scope: *OPTION_DEF_SCOPES
      set: option-def-post

  option-def-specials:
    - match: --(?=\s)
      scope: keyword.control.end-of-options.cmd-help
      set: then-pop
    - match: \+(?=[\s<[:alpha:]])
      scope: keyword.control.plus-option.cmd-help
      set: plus-option-post
    - match: -:(?={{option_break}})
      scope: *OPTION_DEF_SCOPES
      set: option-def-post

  option-def-post:
    - include: option-def-connectors
    - match: '='
      set: option-def+equals
    # match '[=' or '[' or ' [' or ':['
    - match: '\[=|\[| \[|:\['
      set: option-def+square-bracket
    - match: ':'
      set: option-def+colon
    - match: ','
      set: option-def+comma
    - match: '(?=<)'
      set: option-def+space
    - match: ' '
      set: option-def+space
    - include: else-pop

  option-def-connectors:
    - match: ', '
      set: option-def-alt
    - match: ' \| '
      set: option-def-alt
    - match: ' (?=-)'
      set: option-def-alt
    - match: ' or '
      set: option-def-alt
    - match: '  or  '
      set: option-def-alt
    - match: '/'
      set: option-def-alt
    - match: '\s+(?=-)'
      set: option-def-alt

  option-def-alt:
    - include: option-def
    - include: else-pop

  ### option arguments #########################################################

  option-def+space:
    - match: <.*?>
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - match: '{{allcaps_argument_name}}\b'
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - match: '{{relaxed_argument_name}}(?! [:alpha:])'
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - match: '{{relaxed_argument_name}}(?= or )'
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - match: "'{{relaxed_argument_name}}'"
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - match: '{'
      set: option-argument-curly-bracket
    - include: else-pop

  option-def+equals:
    - match: '{{relaxed_argument_name}}'
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - match: <.*?>
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - match: '{'
      set: option-argument-curly-bracket
    - include: else-pop

  option-def+square-bracket:
    - meta_content_scope: *OPTION_ARGUMENT_SCOPES
    - match: '\|'
      push: de-scope-match
    - match: (?=])
      set:
        - match: ']'
          set: option-argument-post

  option-def+colon:
    - match: <.*?>
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - include: else-pop

  option-def+comma:
    - match: <.*?>
      scope: *OPTION_ARGUMENT_SCOPES
      set: option-argument-post
    - include: else-pop

  option-argument-curly-bracket:
    - meta_content_scope: *OPTION_ARGUMENT_SCOPES
    # match ',' or '|'
    - match: ',|\|'
      push: de-scope-match
    - match: (?=})
      set:
        - match: '}'
          set: option-argument-post

  option-argument-post:
    - include: option-def-connectors
    - match: ({{ellipsis}})?
      scope: *OPTION_ARGUMENT_SCOPES
    # match '[=' or '['
    - match: '\[=|\['
      set: option-def+square-bracket
    - match: ',\['
      set: option-def+square-bracket
    - match: '='
      set: option-def+equals
    - match: '\|'
      set: option-def+space
    - include: else-pop

  plus-option-post:
    - match: <.*?>
      scope: *OPTION_ARGUMENT_SCOPES
      set: then-pop
    # e.g.: "LINE:COLUMN" (from emacs)
    - match: '{{allcaps_argument_name}}(:{{allcaps_argument_name}})*'
      scope: *OPTION_ARGUMENT_SCOPES
      set: then-pop
    - include: else-pop

  ### other definitions ########################################################

  argument-def:
    - match: <{{relaxed_argument_name}}>({{ellipsis}})?
      scope: *ARGUMENT_DEF_SCOPES
      set: then-pop
    - match: '{'
      set: curly-bracket-argument-def
    - match: -(?=  )
      scope: *ARGUMENT_DEF_SCOPES # stdin
      set: then-pop
    - match: ({{relaxed_argument_name}}) ({{ellipsis}})
      captures:
        1: *ARGUMENT_DEF_SCOPES
        2: *ARGUMENT_DEF_SCOPES
      set: then-pop

  curly-bracket-argument-def:
    - meta_content_scope: *ARGUMENT_DEF_SCOPES
    # match ',' or '|'
    - match: ',|\|'
      push: de-scope-match
    - match: (?=})
      set:
        - match: '}'
          set: then-pop
    - include: eol-pop

  other-def:
    - include: other-def-escapes
    - include: file-def
    - match: '{{other_lowercase_name}}(?={{long_space}})'
      scope: *OTHER_DEF_SCOPES
      set: then-pop
    # e.g.: "install - install packages (from apt)"
    - match: '{{other_lowercase_name}}(?=\s+-\s+\S)'
      scope: *OTHER_DEF_SCOPES
      set: then-pop
    # e.g.: "compose*" (from docker)
    - match: '{{other_lowercase_name}}\*(?={{long_space}})'
      scope: *OTHER_DEF_SCOPES
      set: then-pop
    # e.g.: "build, b" (from cargo)
    - match: ({{other_lowercase_name}}), ({{other_lowercase_name}})(?={{long_space}})
      captures:
        1: *OTHER_DEF_SCOPES
        2: *OTHER_DEF_SCOPES
      set: then-pop

    - match: '{{allcaps_argument_name}}(?=  )'
      scope: *OTHER_VAL_DEF_SCOPES
      set: then-pop
    # e.g.: "PYTHONSTARTUP:", "PYTHONCASEOK :"
    - match: '{{allcaps_argument_name}}(?=\s*:)'
      scope: *OTHER_VAL_DEF_SCOPES
      set: then-pop
    # e.g.: "'warn'" or "'warn-nopipe'" (from tee)
    - match: "'{{other_lowercase_name}}'"
      scope: *OTHER_VAL_DEF_SCOPES
      set: then-pop

  other-def-escapes:
    # pretty common in "usage:" alternatives
    - match: (?=or\s)
      set: then-pop

  file-def:
    - match: '{{absolute_path}}(?={{long_space}})'
      scope: *FILE_DEF_SCOPES
      set: then-pop
    - match: '{{relative_path}}(?={{long_space}})'
      scope: *FILE_DEF_SCOPES
      set: then-pop
    # dotfile
    - match: '\.{{filename}}(?={{long_space}})'
      scope: *FILE_DEF_SCOPES
      set: then-pop

  ### notable exceptions #######################################################

  color-escape-codes-sink:
    # normal colors fg
    - match: '{{color_code_begin}}3[0-7]{{color_code_end}}'
      set: sink
    # bright colors fg
    - match: '{{color_code_begin}}9[0-7]{{color_code_end}}'
      set: sink
    # normal colors bg
    - match: '{{color_code_begin}}4[0-7]{{color_code_end}}'
      set: sink
    # bright colors bg
    - match: '{{color_code_begin}}10[0-7]{{color_code_end}}'
      set: sink
    # 256 colors fg
    - match: '{{color_code_begin}}38;5;{{color_code_end}}'
      set: sink
    # 256 colors bg
    - match: '{{color_code_begin}}48;5;{{color_code_end}}'
      set: sink
    # RGB colors fg
    - match: '{{color_code_begin}}38;2;{{color_code_end}}'
      set: sink
    # RGB colors bg
    - match: '{{color_code_begin}}48;2;{{color_code_end}}'
      set: sink

  ignore-syntax-test-header:
    - match: '# SYNTAX TEST "cmd-help.sublime-syntax"\n'
      set: main
    - match: ^\n$ # empty line
      set: main

  python-argparse-headings:
    - match: (positional arguments|optional arguments|required arguments|options):\n
      scope: *SECTION_HEADING_SCOPES
      set: then-pop
```

### Expected behavior

Output a correct json.

### Actual behavior

Not a correct json.
