### ISSUE TITLE
`nvim_buf_get_extmark_by_id` has the wrong type in the api

### ISSUE THREAD

**Issue by isovector** [neovim/neovim#21239]
### Neovim version (nvim -v)

bfdddec8bab85340b4b293f1467a56f495e26c2f

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

n/a

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

AUR

### How to reproduce the issue

The return type of `nvim_buf_get_extmark_by_id` is allegedly a `ArrayOf(Integer)`, but this is not true when `opts = {"details": true}`, in which case `nvim_buf_get_extmark_by_id` also returns the details dictionary.

https://github.com/neovim/neovim/blob/bfdddec8bab85340b4b293f1467a56f495e26c2f/src/nvim/api/extmark.c#L208

I think this should be `Array` instead.

### Expected behavior

```
nvim --api-info | python -c 'import msgpack, sys, yaml; yaml.dump(msgpack.unpackb(sys.stdin.buffer.read()), sys.stdout)' | grep extmark_by_id -A10
  name: nvim_buf_get_extmark_by_id
  parameters:
  - - Buffer
    - buffer
  - - Integer
    - ns_id
  - - Integer
    - id
  - - Dictionary
    - opts
  return_type: Array
```

### Actual behavior

```
nvim --api-info | python -c 'import msgpack, sys, yaml; yaml.dump(msgpack.unpackb(sys.stdin.buffer.read()), sys.stdout)' | grep extmark_by_id -A10
  name: nvim_buf_get_extmark_by_id
  parameters:
  - - Buffer
    - buffer
  - - Integer
    - ns_id
  - - Integer
    - id
  - - Dictionary
    - opts
  return_type: ArrayOf(Integer)
```
