### ISSUE TITLE
CI: replace luacheck with luals (for headless/automated linting)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#24563]
### Problem

(This is a tracking issue, to invite discussion/counterpoints/investigation.)

luacheck might be redundant with luals.

### Expected behavior

- determine if luacheck adds value beyond what luals is capable of
- if luals has a non-interactive mode, use that instead of luacheck to check code in CI
    - con: this requires `lintlua` build target to use/install luals
- remove luacheck

**Comment by clason** [comment]
Possible alternative: https://github.com/JohnnyMorganz/luau-lsp, which has a stand-alone mode

(disclaimer: I don't know how close luau is to lua, so whether that can be leveraged at all)

**Comment by lewis6991** [comment]
Luau is almost a completely different language so I'm not sure we can use it.

**Comment by clason** [comment]
https://luau-lang.org claims that

> Luau is syntactically backwards-compatible with Lua 5.1 (code that is valid Lua 5.1 is also valid Luau)

However, it is typed, and I would expect any static analyzer would rely on that rather than our annotations, which would kind of defeat the purpose.

**Comment by clason** [comment]
LuaLS does seem to support a `--check` mode: https://luals.github.io/wiki/usage/

```
lua-language-server/bin/lua-language-server --check runtime --checklevel=Error --logpath=. runtime/
```
> Diagnosis complete, 41 problems found, see ./check.json


[check.json.txt](https://github.com/neovim/neovim/files/12503972/check.json.txt)

Would need some postprocessing...

**Comment by clason** [comment]
Other relevant data points:
* LuaLS can be installed via homebrew
* LuaLS makes frequent (and sometimes breaking) updates; expect reported diagnostics to change rapidly (although if we explicitly extract diagnostics from the JSON, new checks won't be a problem).

**Comment by dundargoc** [comment]
I can't for the life of me get luals used with `--check` to respect the `.luarc.json` config. Unsure if this is the intended behavior. This is gonna be annoying if we can't fix that behavior.

**Comment by Dkendal** [comment]
If it's helpful I set this up on a vim plugin repo like this:

_taskfile_

```yaml
  lint.luasp:
    silent: true
    vars:
      pager:
        sh: command -v tspin || command -v less
    env:
      VIMRUNTIME:
        sh: nvim --clean --headless --cmd 'echo $VIMRUNTIME|q' 2>&1 1>/dev/null
    cmds:
      - ./.tests/xdg/local/share/nvim/mason/bin/lua-language-server --check .  --logpath=.tmp
      - ./tests/nvim -l ./tests/lualsp-report.lua .tmp/check.json | {{.pager}}

```
_./tests/lualsp-report.lua_
```lua
local path = arg[1]

local file = io.open(path, "r")

if not file then
	print("File not found")
	os.exit(1)
end

local json = vim.json.decode(file:read("*a"))

for f, diagnostics in pairs(json) do
	-- remove leading "file://"
	local path = string.sub(f, 8)
	local path_ = vim.fn.fnamemodify(path, ":~:.")
	assert(path_)
	path = path_

	if path:match(".tests/") then
		goto continue
	end

	for _, diagnostic_ in ipairs(diagnostics) do
		--- @class Diagnostic
		--- @field message integer
		--- @field code integer
		--- @field severity integer
		--- @field source string
		--- @field range { ["end"]: { character: integer, line: integer }, start: { character: integer, line: integer } }
		local diagnostic = diagnostic_
		local message = diagnostic.message:gsub("\n", "; ")
		io.write(
			string.format(
				"%s:%s:%s:%s: %s\n",
				path,
				diagnostic.range.start.line,
				diagnostic.range.start.character,
				vim.diagnostic.severity[diagnostic.severity],
				message
			)
		)
	end

	::continue::
end
```
