### ISSUE TITLE
Alacritty 'hints' (clickable patterns, underline on hover) don't work

### ISSUE THREAD

**Issue by OJFord** [neovim/neovim#27006]
### Problem

No underline on mouse-enabled alacritty hints on hover, clicking them does nothing.

### Steps to reproduce

Add a hint to `alacritty.toml` like:
```toml
[[hints.enabled]]
regex = "[a-z]+.com"

[hints.enabled.command]
program = "sh"
args = ["-c", 'xdg-open "https://$0"']

[hints.enabled.mouse]
enabled = true
mods = "None"
```

Run `nvim --clean`, so `set mouse` is `nvi`.

Enter insert mode and type `example.com`

### Expected behavior

`example.com` should be underlined on highlight. Clicking it should open it in the default browser.

### Neovim version (nvim -v)

0.9.5

### Vim (not Nvim) behaves the same?

No, it works in vim 9.1

### Operating system/version

Linux 6.6.10

### Terminal name/version

alacritty 0.13.1

### $TERM environment variable

alacritty

### Installation

system package manager (arch extra)
