### ISSUE TITLE
Add function to the msgpack-rpc-api to call arbitrary functions more conveniently

### ISSUE THREAD

**Issue by saep** [neovim/neovim#2972]
This is a mere suggestion and not urgent at all.

If I want to call arbitrary function on the neovim side, I currently use `vim_command` or `vim_command_output`. 

``` yaml
- can_fail: true
  deferred: true
  name: vim_command
  parameters:
  - [String, str]
  return_type: void

- can_fail: true
  deferred: false
  name: vim_command_output
  parameters:
  - [String, str]
  return_type: String
```

In a statically typed language, it involves quite some overhead to create a function call for that. I have to manually create a valid vimL string from the types I have. Since I already have mechanisms to convert my values into msgpack-rpc objects, wouldn't it be convenient to just use these directly? I have a function like this in mind.

``` yaml
- can_fail: true
  deferred: false
  name: vim_function
  parameters:
  - [String, functionName]
  - [ArrayOf(Object), args]
  return_type: Object
```

I can achieve a similar behaviour with `vim_command_output` by creating higher order functions (or whatever) in the language I am writing a plugin in. But that is quite some overhead and another serialization I have to implement even though the msgpack-rpc serialization is already there. There may still be use-cases where you have to create vimL by hand, but I think this is one that deserves an API function.

As a motivating example, take the function `setqflist`. It takes a dictionary with a few mandatory values. If I already have a dictionary in my plugin language, then I can simply use a function like `toMSGPack` to convert it to an argument for `vim_function`. Otherwise, I have to create a string representation from the map that is valid vimL.

The only downside I see with this is that there is one more function in the API.

One noteworthy upside is that you only have to do this work once on the neovim side and not necessarily in all languages that plugins can be written in. There may even be language dependent advantages for doing this (e.g. static guarantees for argument values).

I would start creating a pull request if this is deemed to be useful.
