### ISSUE TITLE
Wrong indentation when paste with <C-r>" in insert mode

### ISSUE THREAD

**Issue by johannww** [neovim/neovim#33236]
### Problem

Indentation is not respected when pasting with <C-r>":

```yaml
# Original paragraph copied:
- import_playbook: delete-network.yaml
  when:
  - reset is defined and reset == 'true'
  - network.env.type != 'operator'

# Pasting with p in normal mode
- import_playbook: delete-network.yaml
  when:
  - reset is defined and reset == 'true'
  - network.env.type != 'operator'

# Pasting with <C-r>" in insert mode
- import_playbook: delete-network.yaml
  when:
    - reset is defined and reset == 'true'
      - network.env.type != 'operator'

```

### Steps to reproduce

- nvim -u NONE file.yaml
- yank a text block
- paste in insert mode with the bind: \<C-r\>"

### Expected behavior

Neovim pastes a text equal to the one copied.

### Nvim version (nvim -v)

v0.11.0 (it works great on asdf v0.10.4 )

### Vim (not Nvim) behaves the same?

Yes, on vim v9.1.1236

### Operating system/version

arch-linux 6.12.21-1-lts

### Terminal name/version

alacritty/alacritty 0.15.1 (0c405d53) | ghostty/Ghostty 1.1.3-arch1

### $TERM environment variable

tmux-256color

### Installation

aur
