### ISSUE TITLE
YAML syntax highlighting

### ISSUE THREAD

**Issue by burningTyger** [neovim/neovim#4975]
- `nvim --version`: NVIM v0.1.4-179-ga7a0bf5
- Vim (version: ) behaves differently?
- Operating system/version: Arch Linux
- Terminal name/version: Gnome Terminal
- `$TERM`: xterm-256color

This yaml snippet:
```yaml
---
Textbausteine:
  Text: >
    Some longer text
    #{some code}, xxxxx
    more text
```
### Actual behaviour
`#{some code}, xxxxx` is highlighted as comment

### Expected behaviour
`#{some code}, xxxxx` should be highlighted as string

### Steps to reproduce using `nvim -u NORC`
?
```
nvim -u NORC

```
