### ISSUE TITLE
API: ui_try_resize() return type changed since 0.1.5

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#5388]
Listing the API with

```
nvim --api-info | python -c 'import msgpack, sys, yaml; print yaml.dump(msgpack.unpackb(sys.stdin.read()))'
```

shows different signatures for ui_try_resize

### 0.1.5

```
- async: false
  can_fail: true
  name: ui_try_resize
  parameters:
  - [Integer, width]
  - [Integer, height]
  receives_channel_id: true
  return_type: Object
```

### 0.1.6-143-g68bcb32

```
- async: false
  can_fail: true
  deprecated_since: 1
  impl_name: nvim_ui_try_resize
  method: false
  name: ui_try_resize
  noeval: true
  parameters:
  - [Integer, width]
  - [Integer, height]
  receives_channel_id: true
  return_type: void
```

The return type was changed in #4432, later #4934 adds the new variant nvim_ui_try_resize.

Maybe we can automate verification against a saved api metadata from an earlier release.
