### ISSUE TITLE
API: nvim_get_commands()

### ISSUE THREAD

**Issue by varmanishant** [neovim/neovim#7833]
- `nvim --version`: v0.2.3-384-g7c4bb23ff
- Vim (version: ) behaves differently? No
- Operating system/version: Linux
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
:command

```

### Actual behaviour

The output is misaligned

### Expected behaviour

A clean output since it exposes all the API's! Is there any ideas to make this better? It is a cosmetic issue but something that needs to be improved.

**Comment by justinmk** [comment]
Nvim has `nvim_get_keymap()` for programmatically accessing global and buffer-local maps. Sounds like you want something similar for command, e.g. `nvim_get_commands()`.

**Comment by ZyX-I** [comment]
I find this close to useless, better have an API function to get information about command instead. Also it never lists customlist arguments. Something like `nvim[_buf]_get_commands()` returning array of

```YAML
name: # Command name
nargs: # Number of arguments, ASCII character constant (i.e. 7-bit integer)
complete: # Completion argument, full (i.e. for `customlist` it would be `customlist,Foo`)
ftype: # "none" or same as `complete`: `-complete=file` changes arguments handling
       # too significantly to be just completion.
range: # Range, string: ".", "%", "" or stringified number
count: # Boolean, if true means that `range: "100"` is actually `-count=100`
addr: # String
bar: # Boolean
bang: # Boolean
register: # Boolean
```
